## -*- encoding: utf-8 -*-
## This file (GeometryMain.sagetex.sage) was *autogenerated* from GeometryMain.tex with sagetex.sty version 2019/01/09 v3.3.
import sagetex
_st_ = sagetex.SageTeXProcessor('GeometryMain', version='2019/01/09 v3.3', version_check=True)
try:
 _st_.current_tex_line = 19
 _st_.inline(0, latex(1+2+sqrt(3)))
except:
 _st_.goboom(19)
try:
 _st_.current_tex_line = 23
 _st_.plot(0, format='notprovided', _p_=plot(sin(x), x, 0, 2*pi))
except:
 _st_.goboom(23)
_st_.endofdoc()
